<a href="https://colab.research.google.com/github/SunilAshish/trial_pytorch_repository/blob/main/trial_pytorch_lecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [2]:
#!pip list

In [3]:
import numpy as np

**Lists**

In [7]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [8]:
my_list=[[1,2,3,4],[4,3,2,1]]
my_list

[[1, 2, 3, 4], [4, 3, 2, 1]]

**Array**

In [11]:
np1=np.random.rand(3,4)
np1

array([[0.30235016, 0.03846667, 0.16982019, 0.79205456],
       [0.848421  , 0.16664015, 0.32522213, 0.02811808],
       [0.05989417, 0.11605305, 0.66595881, 0.85397978]])

In [13]:
print(np1.dtype)

float64


**Tensor**

In [14]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-0.1493, -0.6093, -0.4581, -1.0535],
        [ 0.9218, -0.4331,  0.2306,  0.1331],
        [ 0.5374,  0.3302,  0.0144, -0.6951]])

In [20]:
tensor_2d.dtype

torch.float32

In [19]:
tensor_3d=torch.randn(2,4,5)
tensor_3d

tensor([[[-0.2187, -0.4908,  0.3793,  0.0064,  0.3410],
         [-0.5054, -0.1805,  0.9692, -0.2173,  0.0839],
         [ 1.6226, -1.5453,  0.1707, -0.6926,  1.1733],
         [-0.1936,  0.2800, -2.4748,  0.9282, -0.4144]],

        [[ 2.2594,  0.1558,  0.9350, -2.2644, -1.2709],
         [-0.4360,  2.0452,  1.6415, -0.8073,  0.7795],
         [ 0.6099, -0.4546, -0.3502,  0.3218,  0.6317],
         [ 1.2827,  1.0919, -0.7005, -0.7850,  0.4232]]])

In [18]:
#Converting Numpy to Tensor
tensor_from_numpy=torch.from_numpy(np1)
tensor_from_numpy

tensor([[0.3024, 0.0385, 0.1698, 0.7921],
        [0.8484, 0.1666, 0.3252, 0.0281],
        [0.0599, 0.1161, 0.6660, 0.8540]], dtype=torch.float64)

**# Tensor Operations**

In [23]:
 #Reshaping tensor
 my_tensor=torch.arange(10)
 my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
reshped_tensor=my_tensor.reshape(2,5)
reshped_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
#If we don't know the number of data points but know how many rows we want
reshaped_tensor=my_tensor.reshape(5,-1)
reshaped_tensor

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [28]:
#If we don't know the number of data points but know how many rows we want
reshaped_tensor1=my_tensor.reshape(-1,5)
reshaped_tensor1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
#View and Reshape
reshaped_tensor1=my_tensor.view(-1,5)
reshaped_tensor1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

*Changing tensor element change automatically in every where*

In [30]:
my_tensor[0]=1000;
my_tensor

tensor([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [31]:
reshaped_tensor1

tensor([[1000,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

**Slicing**

In [32]:
#Slicing
my_tensor[1]

tensor(1)

In [34]:
reshaped_tensor1[:,2]

tensor([2, 7])

In [37]:
# Returning column'
reshaped_tensor1[:,4:]

tensor([[4],
        [9]])

**Tensor Math Operation**

*Add, Subtract,Multiply,Divide,Remainders,Exponents*


In [4]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])
add_tensor=tensor_a+tensor_b
add_tensor

tensor([ 6,  8, 10, 12])

In [5]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
#Subtract
sub_tensor=tensor_a-tensor_b
sub_tensor

tensor([-4, -4, -4, -4])

In [7]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [8]:
#multiplication
prod_tensor=tensor_a*tensor_b
prod_tensor

tensor([ 5, 12, 21, 32])

In [10]:
torch.multiply(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
#Division
div_tensor=tensor_a/tensor_b
div_tensor

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [12]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [16]:
#Remainder
rem_tensor=tensor_b%tensor_a
rem_tensor

tensor([0, 0, 1, 0])

In [17]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [22]:
#Exponents
print(tensor_a,tensor_b)
torch.pow(tensor_b,tensor_a)

tensor([1, 2, 3, 4]) tensor([5, 6, 7, 8])


tensor([   5,   36,  343, 4096])

In [25]:
#Longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
#Reassign elements to tensor
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [28]:

tensor_a

tensor([ 6,  8, 10, 12])